### ISSUE TITLE
[Multiple Crystal-Errors] -> not buildable

### ISSUE THREAD

**Issue by JimDoesntCarry** [repomaa/cgit-auth#1]
Hi,

i tried building the project but I think it's not maintained / buildable anymore.

Examples:

in src/cgit-auth/config.cr
> line 4 > comma "," missing on end of line

in src/cgit-auth/session.cr
> line 12 > some problem with .value and parenthesis
> line 32 > some problem with "as UInt8*" and paranthesis

Maybe I should fork and publish my fixes, but I have to learn crystal for that ^^

**Comment by repomaa** [comment]
Hey! Thanks for reaching out. I have literally no recollection of ever writing this but I’d be happy to bring it up to speed. A lot has changed in crystal since this was written, but it’s not a complex project so I should be able to port it pretty quickly.

**Comment by repomaa** [comment]
@JimDoesntCarry i pushed some changes and it compiles at least, want to give it a try?

**Comment by JimDoesntCarry** [comment]
Thank you very much!
Didn't look deep into it yet but it builds now <3
